services:
  traefik:
    image: traefik:v3.7.13
    container_name: global-traefik
    restart: always
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      
      # Entrypoints for HTTP (80) and HTTPS (443)
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"

      # Automatic HTTP to HTTPS Redirection
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"

      # Let's Encrypt (ACME) Certificate Resolver
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${ACME_EMAIL}" 
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/opt/stacks/traefik/acme.json:/letsencrypt/acme.json"
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true