name: Deploy Main
on:
  push:
    branches: ["main"]
jobs:
  call-deploy:
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      environment: main
      target_dir: /opt/stacks/main
    secrets: inherit